### ISSUE TITLE
mgmsampler from a fitted mgm object

### ISSUE THREAD

**Issue by yqzhong7** [jmbh/mgm#14]
Is there a simple way to simulate the data based on a fitted `mgm` object? The arguments of `mgmsampler` do not match the return values from `mgm`.

Take your autism_data as example,
``` r
data("autism_data")
fit_k2 <- mgm(data = autism_data$data,
              type = autism_data$type,
              level = autism_data$lev,
              k = 2) # ad most pairwise interacitons
```

How can I use `fit_k2` to simulate data with `mgmsampler`?

``` r
interactions <- list(lapply(fit_k2$interactions$weightsAgg[[1]],function(x) array(x[[1]],dim=c(1,1))))
thresholds <- vector("list", length = ncol(W))
thresholds <- lapply(thresholds, function(x) 0 ) 
simDAT <-mgmsampler(factors = fit_k2$interactions$indicator,
                    interactions = interactions,
                    thresholds = thresholds,
                    sds = rep(.1, length(autism_data$type)),
                    type =autism_data$type,
                    level =autism_data$lev)
```
This yields an error:
``` r
#> Error in mgmsampler(factors = fit_k2$interactions$indicator, interactions = interactions,  : 
#>                      The dimensions of the interaction 1-2 is specified incorrectly. Please correct the 'interactions' argument.
```

**Comment by jmbh** [comment]
Hi Yongqi Zhong, 

I agree with you that this should be possible. However, currently it is not, because mgmsampler() uses a different (overparameterized) parameterization than the estimation functions.

If I revamp the package again at some point I'll make sure to allow using the output of the estimation functions as an alternative input to the sampling functions.

Best wishes,
Jonas
