### ISSUE TITLE
getting around checks in glmnetRequirements()

### ISSUE THREAD

**Issue by leeyang** [jmbh/mgm#2]
Hi,jmbh
sorry for my  mistake!
some of my data cannot pass the 'glmnetRequirements' test, including the second and the third condition in glmnetRequirements because of the poor data quality. I have tried tracing mgm function and remove glmnetRequirements code. The code runs for a while and quit with 
` Error in lognet(x, is.sparse, ix, jx, y, weights, offset, alpha, nobs,  : 
  one multinomial or binomial class has 1 or 0 observations; not allowed In addition: Warning messages:
1: In lognet(x, is.sparse, ix, jx, y, weights, offset, alpha, nobs,  :
  one multinomial or binomial class has fewer than 8  observations; dangerous ground
2: from glmnet Fortran code (error code -19); Convergence for 19th lambda value not reached after maxit=100000 iterations; solutions for larger lambdas returned 
3: In lognet(x, is.sparse, ix, jx, y, weights, offset, alpha, nobs,  :
  one multinomial or binomial class has fewer than 8  observations; dangerous ground
4: from glmnet Fortran code (error code -19); Convergence for 19th lambda value not reached after maxit=100000 iterations; solutions for larger lambdas returned `
 It seems that it is a problem of glmnet...It could be hard to handle this.  Any suuggestions?

**Comment by jmbh** [comment]
Hi leeyang, 

The glmnetRequirements() function is there to give informative error messages, if data does not satisfy the requirements of glmnet, which is used inside mgm for estimation. If you remove these checks, you get the (I think) less informative error messages of glmnet.

This means there is no way around this error. 

However, note that if you have only a couple of observations for a category, you probably cannot expect any stable estimates for this category anyway. So probably the best solution would be to exclude those cases or to collapse them into other categories, if that makes sense for your data.

Another "fix" would be to use the EBIC instead of cross-validation to select the regularization parameter lambda. This alleviates the problem to a small extent, because when using cross validation (the default), at least 2 observations of each category have to be present in the training set of _each fold_. When using the EBIC, this is only required for the whole dataset. However, personally I would not recommend that, because cross validation has a clearer notion of optimality in your data, and again, you might "pass" the glmnet requirements, but your estimates will still be very unstable.

Cheers,
Jonas

**Comment by leeyang** [comment]
Hi jmbh,
Thanks for your HELP!
After replacing some observations with other categories, It works fine until now. 
By the way, I have a dataset with 100 category variables, each variables has 15 classes, and 5000 observations. 
when I use default setting("CV") mode the program stack at 6% after 8 hours.
Then I set: lambdaSel="EBIC", alphaSel="EBIC", After 7 hours, It reaches to 20%. seems that I have to wait another 28 hours...
Is that normal?
Anything I can do to accelerate this?

**Comment by jmbh** [comment]
Hi leeyang, 

Could you open a new issue for this?

Thanks,
Jonas
