### ISSUE TITLE
Warning with Registered S3 methods

### ISSUE THREAD

**Issue by HaileyKUANG** [jmbh/mgm#29]
Warning: package ‘mgm’ was built under R version 4.3.2Registered S3 methods overwritten by 'htmltools':
  method               from         
  print.html           tools:rstudio
  print.shiny.tag      tools:rstudio
  print.shiny.tag.list tools:rstudio
Registered S3 method overwritten by 'htmlwidgets':
  method           from         
  print.htmlwidget tools:rstudio
Registered S3 method overwritten by 'data.table':
  method           from
  print.data.table     
This is mgm 1.2-14
Please report issues on Github: https://github.com/jmbh/mgm/issues

**Comment by jmbh** [comment]
Thanks for reporting this. 

This just says that 1) your R-version is older than the one that was used to build mgm; this does not have to be a problem, but to be sure it would be good to update your R. 2) That some S3 methods are overwritten. You can make sure to access the right S3 method, by using, for example print.mgm() instead of print().
