### ISSUE TITLE
Error - "class has 1 or 0 observations"

### ISSUE THREAD

**Issue by IrinaVanzhula** [jmbh/mgm#6]
Hi Jonas,

I am having trouble with running mgm model. I think it has something to do with how my data is formatted, but I am stuck and can't figure it out. I have no missing data and made sure that all variables have variance. Majority of variables are categorical (marked as "c" and others are ordinal (marked as "g")
 
I get the following error message: r in lognet(x, is.sparse, ix, jx, y, weights, offset, alpha, nobs,  : 
  one multinomial or binomial class has 1 or 0 observations; not allowed

Here is my code:
library(mgm)
library(qgraph)
data <- read.table("C:/Users/Irina/Dropbox/PAPERS/LABS/BBnetworkNM3.csv", header=TRUE, sep=",")
fit_mgm <- mgm(data = as.matrix(data),
               type = c("c", "c", "c", "c", "g", "c", "c", "g", "c", "c", 
                        "c", "c", "c", "c", "c", "g", "g", "g"),
               levels = c(2, 2, 2, 2, 1, 2, 2, 1, 2, 2,
                          2, 2, 2, 2, 2, 1, 1, 1), 
               lambdaSel = "CV",
               lambdaFolds = 10,
               ruleReg = "AND", overparameterize = TRUE)

Thanks for your help!

**Comment by jmbh** [comment]
Hi Hautesh, 

The problem is that mgm (actually glmnet which is used internally) needs at least 2 observation of each category of each categorical variable to fit the model. If you use cross-validation for model selection, you need at least 2 observations in the training part of each fold of the cross-validation scheme. In your case there is at least one variable for which this is not the case in at least one fold of the 10-fold cross-validation scheme.

You can work around this problem in a couple of ways:
1. Use different seeds and hope that the problem does not occur; however, this may bias your cross-validation scheme in unexpected ways
2. Use a larger number of folds; if approach leave-one-out cross validation, the likelihood that you have a training set with one or more categories having low frequency becomes smaller, since your training becomes larger
3. Use the EBIC for model selection (lambdaSel = "EBIC")
4. You check which categories have low frequency and collapse them in a meaningful way into other categories. This might not be as bad as it sounds, because if you have little data for some categories you cannot expect to get reliable estimates for them anyways.

Cheers,
Jonas

**Comment by jhoelt** [comment]
Hi Jonas,

First, thanks for this great package. I really like what it can tell about the data.

I have an issue related to this. So when I used cross validation first, I got the same error as hautesh. So now I used EBIC and get the following error seven times:

7: In lognet(x, is.sparse, ix, jx, y, weights, offset, alpha, nobs,  :
  one multinomial or binomial class has fewer than 8  observations; dangerous ground

this is the syntax:
> Botsnm <- na.omit(Bots) # so there are no missings in the dataset
> Botsmgm <- mgm(data = Botsnm, type = rep ("c", 17), level = rep(5, 17), ruleReg = "OR", lambdaSel = "EBIC", scale = TRUE)

I still get a result even with these errors, and when I go a step further to calculate the predictabilities for my nodes by using 
> Botspred2 <- predict(object = Botsmgm, data = Botsnm, errorCat = c("CC", "nCC", "CCmarg"))

I still get something for "CC", "nCC", and "CCmarg", pretty high numbers for CC and CCmarg, but almost nothing for nCC.

This cross-sectional dataset has 511 individuals with no missings and 17 items for the network analysis.

I did the same syntax with a dataset with over 3000 individuals and there were no errors (I'm comparing several networks). So is this related to the sample size? But 500 are still quite high!?

Or would you treat the variables as continuous and just work with errorCon = 'R2'? Because in your paper "How well do Network Models predict Observations? On the Importance of Predictability in Network Models" you treat the (for me) ordinal variables with 3 levels as continuous. When you treat a three level ordinal variable as continuous, do you use the type = "c" only for binary variables? So do you mean with categorical only binary and not ordinal variables? Or when would you define an ordinal variable as "c" and when as "g"? By the way, when should I use type = "p"?

Any suggestions?
Thanks
Jan

**Comment by jmbh** [comment]
Hi Jan, 

You are getting a warning (no error!) from the glmnet function (which is used inside mgm), because at least one of your categorical variables has a category with 8 or less observations. This is likely to lead to inaccurate parameter estimates which is why glmnet returns the warning.

There is many ways of dealing with that like not doing anything about it but assessing the accuracy of parameter estimates (e.g. via bootstrapping), dropping cases, or collapsing categories. Unfortunately, there is no principled way to decide which is better as long as you don't assume a data generating distribution (which you typically don't have). Then you could determine the performance of different options via simulation.

Cheers,
Jonas
